import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,writeFile}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';
import{classifyBedfordDrawing,discoverBedfordDrawings,inspectPdf,parseOptions,writeIntakeOutputs}from'../scripts/ingest-bedford-drawings.mjs';import{createCampusDrawingManifest,deterministicManifestJson,stableDrawingSetId,validateCampusDrawingManifest}from'../src/campus-drawing-manifest.js';
const pdf=pages=>Buffer.from(`%PDF-1.7\n1 0 obj\n<< /Type /Pages /Count ${pages} >>\nendobj\n%%EOF`,'latin1');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'mc-bedford-intake-'));const source=join(root,'drawings');await mkdir(source);return{root,source};}
test('discovery finds case-insensitive PDFs, ignores hidden/non-PDF/README, rejects zero-byte, and deduplicates fingerprints',async()=>{const{source}=await fixture();await Promise.all([writeFile(join(source,'B08-set.pdf'),pdf(54)),writeFile(join(source,'B61-copy.PDF'),pdf(54)),writeFile(join(source,'.hidden.pdf'),pdf(2)),writeFile(join(source,'notes.txt'),'x'),writeFile(join(source,'README.md'),'x'),writeFile(join(source,'zero.pdf'),'')]);const result=await discoverBedfordDrawings({sourceDir:source,concurrency:2});assert.equal(result.discoveredCount,3);assert.equal(result.records.length,1);assert.equal(result.duplicates.length,1);assert.deepEqual(result.failures,[{file:'zero.pdf',reason:'zero-byte-or-not-file'}]);assert.ok(result.peakConcurrency<=2);});
test('streaming PDF inspection returns fingerprint, byte size, and structural page count',async()=>{const{source}=await fixture(),path=join(source,'B08.pdf');await writeFile(path,pdf(88));const result=await inspectPdf(path);assert.equal(result.pageCount,88);assert.equal(result.fingerprint.length,64);assert.ok(result.byteSize>0);});
test('building classification is bounded to explicit tokens and named assets',()=>{const item=name=>classifyBedfordDrawing({sourceFileName:name,pageCount:20,fingerprint:'a'.repeat(64),byteSize:10});assert.equal(item('Bedford.B78A.IFC.pdf').buildingId,'78A');assert.equal(item('Bedford.B78_78A.IFC.pdf').buildingId,'78-78A');assert.equal(item('Bedford.MCR.IFC.pdf').buildingId,'MCR');assert.equal(item('Bedford.BCH.IFC.pdf').buildingId,'CRESCENT-HOUSE');assert.equal(item('Bedford.SITE.IFC.pdf').buildingId,'SITE');assert.equal(item('Bedford.Crescent House.IFC.pdf').buildingId,'CRESCENT-HOUSE');assert.equal(item('518-22-700.Room124.pdf').buildingId,'');assert.equal(item('518-22-700.Room124.pdf').classificationState,'needs-review');});
test('verified title-block and drawing-index evidence outrank filename inference',()=>{const base={sourceFileName:'Bedford.B08.IFC.pdf',pageCount:20,fingerprint:'1'.repeat(64),byteSize:10};const title=classifyBedfordDrawing({...base,classificationText:'BUILDING NUMBER: 62\nSHEET NUMBER 62A-101'});assert.equal(title.buildingId,'62');assert.ok(title.titleBlockEvidence.includes('title block building 62'));const index=classifyBedfordDrawing({...base,classificationText:'70G-001 DRAWING INDEX'});assert.equal(index.buildingId,'70');assert.ok(index.titleBlockEvidence.includes('drawing index sheet 70G-001'));});
test('specification-like documents are unsupported drawing inputs',()=>{const record=classifyBedfordDrawing({sourceFileName:'518-22-700.Bedford.Specifications.B61.pdf',pageCount:2363,fingerprint:'b'.repeat(64),byteSize:20});assert.equal(record.documentType,'specifications');assert.equal(record.classificationState,'unsupported');});
test('manual overrides outrank filename evidence',()=>{const record=classifyBedfordDrawing({sourceFileName:'ambiguous.pdf',pageCount:20,fingerprint:'c'.repeat(64),byteSize:20,override:{buildingId:'8',documentType:'drawing-set'}});assert.equal(record.buildingId,'8');assert.equal(record.classificationState,'classified');assert.equal(record.classificationConfidence,.99);});
test('Building 61 fixture requires exact filename and 70 pages',()=>{const input={sourceFileName:'518-22-700.Bedford.EHRM.IFC.B61.20260316.pdf',fingerprint:'d'.repeat(64),byteSize:20};const ready=classifyBedfordDrawing({...input,pageCount:70});assert.equal(ready.buildingId,'61');assert.equal(ready.catalogState,'ready');assert.equal(ready.indexPage,2);assert.equal(ready.indexSheetNumber,'61G-001');const mismatch=classifyBedfordDrawing({...input,pageCount:69});assert.equal(mismatch.classificationState,'needs-review');assert.equal(mismatch.catalogState,'profile-mismatch');assert.equal(classifyBedfordDrawing({...input,sourceFileName:'Bedford.B62.pdf',pageCount:70}).generatedCatalogPath,'');});
test('manifest IDs and JSON are deterministic and contain no PDF bytes',()=>{const record=classifyBedfordDrawing({sourceFileName:'Bedford.B08.pdf',pageCount:54,fingerprint:'e'.repeat(64),byteSize:20});assert.equal(stableDrawingSetId(record),record.drawingSetId);const first=createCampusDrawingManifest([record],{generatedAt:'2026-08-02T00:00:00Z'}),second=createCampusDrawingManifest([record],{generatedAt:'2026-08-02T00:00:00Z'});assert.equal(deterministicManifestJson(first),deterministicManifestJson(second));assert.equal(validateCampusDrawingManifest(first).valid,true);assert.equal(deterministicManifestJson(first).includes('pdfBytes'),false);});
test('manifest validation detects malformed identities, unsafe paths, and byte fields',()=>{const manifest=createCampusDrawingManifest([],{generatedAt:'x'});manifest.drawingSets=[{drawingSetId:'',sourceFileName:'bad.pdf',classificationState:'ready-for-catalog',buildingId:'',generatedCatalogPath:'../bad',pdfBytes:'forbidden'}];const result=validateCampusDrawingManifest(manifest);assert.equal(result.valid,false);assert.ok(result.errors.length>=4);});
test('full output writes campus, building, Building 61 catalog, and concise reports',async()=>{const{root}=await fixture(),dataDir=join(root,'data');const record=classifyBedfordDrawing({sourceFileName:'518-22-700.Bedford.EHRM.IFC.B61.20260316.pdf',pageCount:70,fingerprint:'f'.repeat(64),byteSize:20});await writeIntakeOutputs({records:[record],duplicates:[],failures:[],discoveredCount:1,peakConcurrency:1},{dataDir,generatedAt:'2026-08-02T00:00:00Z'});for(const path of['manifests/campus-drawing-manifest.json','buildings/61/drawing-set.json','drawing-catalogs/building-61.json','reports/drawing-intake-report.json','reports/drawing-intake-report.md'])assert.ok((await readFile(join(dataDir,path))).length);const files=await readdir(join(dataDir,'drawing-catalogs'));assert.deepEqual(files,['building-61.json']);const catalog=JSON.parse(await readFile(join(dataDir,'drawing-catalogs/building-61.json'),'utf8'));assert.equal(catalog.sheets.length,70);});
test('dry-run options are safe and concurrency is capped at two',()=>{assert.deepEqual(parseOptions(['--dry-run','--concurrency=99','--building=61']),{dryRun:true,validate:false,concurrency:2,file:'',building:'61',force:false,verbose:false});});
