import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeSubmittalRow, setRecordOverride } from '../src/structured-records.js';
import { selectRelevantProjectRecords, buildProjectRecordContext } from '../src/chief-project-record-context.js';
import { buildChiefContext, setActiveProjectRecordContext, clearActiveProjectRecordContext } from '../src/chief-context-adapter.js';

test('Chief context uses effective submittal values and preserves source provenance', () => { const record = setRecordOverride(normalizeSubmittalRow({ Number: '28 23 00-1', Status: 'Open' }, { projectId: 'bedford', sourceDocumentId: 'source-1' }), 'status', 'Approved', 'Review complete'); const selected = selectRelevantProjectRecords([record], 'What is the status of submittal 28 23 00-1?', { projectId: 'bedford' }); assert.equal(selected[0].effective.status, 'Approved'); assert.equal(selected[0].sourceValue.status, 'Open'); assert.match(buildProjectRecordContext(selected), /CURRENT PROJECT VALUE/); assert.match(buildProjectRecordContext(selected), /SOURCE-REPORTED VALUE/); });
test('selected record scopes context and unrelated records are excluded', () => { const a = normalizeSubmittalRow({ Number: 'S-1', Status: 'Open' }, { projectId: 'bedford' }); const b = normalizeSubmittalRow({ Number: 'S-2', Status: 'Open' }, { projectId: 'bedford' }); assert.equal(selectRelevantProjectRecords([a, b], 'What is the schedule?', { projectId: 'bedford', selectedRecordId: 'bedford:submittal:S-1' }).length, 1); assert.equal(selectRelevantProjectRecords([a, b], 'What is the schedule?', { projectId: 'bedford' }).length, 0); });
test('active shell record context reaches Chief context and clears on navigation', () => { setActiveProjectRecordContext('bedford:activity:A-10'); assert.equal(buildChiefContext({ surface: 'schedule' }).projectRecordId, 'bedford:activity:A-10'); clearActiveProjectRecordContext(); assert.equal(buildChiefContext({ surface: 'overview' }).projectRecordId, ''); });
