import test from 'node:test'; import assert from 'node:assert/strict';
import { createConstructionGraph, normalizeConstructionNode } from '../src/construction-graph.js';
import { adaptPmisRecordToGraph } from '../src/construction-graph-adapters.js';
import { buildChiefConstructionGraphContext } from '../src/chief-construction-graph-context.js';
const memory=()=>{const records={nodes:[],edges:[],history:[]};return{records,loadNodes:async()=>records.nodes,loadEdges:async()=>records.edges,putNode:async r=>{records.nodes=records.nodes.filter(x=>x.nodeId!==r.nodeId).concat(structuredClone(r));},putEdge:async r=>{records.edges=records.edges.filter(x=>x.edgeId!==r.edgeId).concat(structuredClone(r));},putHistory:async r=>records.history.push(structuredClone(r))};};
export function graphFixture(){const persistence=memory(),graph=createConstructionGraph({persistence});graph.registerNode({nodeId:'page',projectId:'p',nodeType:'drawing-page',label:'61IN101',sourceSystem:'catalog',verificationState:'confirmed',origin:'imported'});graph.registerNode({nodeId:'finish',projectId:'p',nodeType:'construction-object',label:'Finish P-1',sourceSystem:'registry',sourceObjectId:'finish',verificationState:'confirmed',origin:'manual'});graph.registerNode({nodeId:'paint',projectId:'p',nodeType:'specification-section',label:'09 91 00 Painting',sourceSystem:'spec-index',verificationState:'confirmed',origin:'imported'});graph.registerEdge({projectId:'p',sourceNodeId:'page',targetNodeId:'finish',edgeType:'contains',scope:'page',confidence:1,verificationState:'confirmed',origin:'imported'});graph.registerEdge({projectId:'p',sourceNodeId:'finish',targetNodeId:'paint',edgeType:'governed-by',scope:'object',confidence:1,verificationState:'confirmed',origin:'manual'});return{graph,persistence};}
test('stable nodes, idempotent edges, paths, and incremental persistence',async()=>{const {graph,persistence}=graphFixture();graph.registerNode({nodeId:'finish',projectId:'p',nodeType:'construction-object',label:'Renamed Finish',sourceSystem:'registry',verificationState:'confirmed',origin:'manual'});assert.equal(graph.getNode('finish').nodeId,'finish');const before=graph.getDiagnostics('p').edgeCount;graph.registerEdge({projectId:'p',sourceNodeId:'finish',targetNodeId:'paint',edgeType:'governed-by',verificationState:'confirmed',origin:'manual'});assert.equal(graph.getDiagnostics('p').edgeCount,before);assert.deepEqual(graph.getPath('page','paint',{projectId:'p'}).nodes.map(x=>x.nodeId),['page','finish','paint']);await graph.flush();assert.equal(persistence.records.nodes.length,3);assert.equal(persistence.records.edges.length,2);});
test('cross-project edges and unsupported nodes are rejected',()=>{const {graph}=graphFixture();graph.registerNode({nodeId:'foreign',projectId:'other',nodeType:'room',label:'124',sourceSystem:'manual',origin:'manual'});assert.equal(graph.registerEdge({projectId:'p',sourceNodeId:'finish',targetNodeId:'foreign',edgeType:'located-in',origin:'manual'}),null);assert.equal(normalizeConstructionNode({projectId:'p',nodeType:'future-fabrication',label:'x'}),null);});
test('construction summary groups requirements and leaves missing readiness unknown',()=>{const {graph}=graphFixture();const summary=graph.getConstructionSummary('finish');assert.equal(summary.requirements.confirmed[0].node.nodeId,'paint');assert.equal(summary.readiness,null);});
test('PMIS adapter retains source ownership and Chief graph context is read only',()=>{const{graph}=graphFixture();const risk=adaptPmisRecordToGraph(graph,{projectId:'p',operationType:'risk',recordId:'risk-12',title:'Finish approval',status:'open',updatedAt:'2026-08-01'});graph.registerEdge({projectId:'p',sourceNodeId:'finish',targetNodeId:risk.nodeId,edgeType:'affected-by',verificationState:'confirmed',origin:'imported'});const context=buildChiefConstructionGraphContext({graph,projectId:'p',selectedObjectId:'finish'});assert.equal(risk.sourceSystem,'pmis');assert.equal(context.readOnly,true);assert.equal(context.operationalRecords[0].node.sourceRecordId,'risk-12');assert.equal(context.mutate,undefined);});
