import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { applyPageObjectEnrichment, collectPageObjectEvidence, enrichPageConstructionObjects, relatedObjectIdsForSelection } from '../src/drawing-object-enrichment.js';
import { createProjectObjectRegistry } from '../src/project-object-registry.js';
import { hitTestDrawingObjects } from '../src/drawing-object-interaction.js';

const region=(x,y,width=.03,height=.02)=>({x,y,width,height});
const observation=(id,value,x,y,kind='positioned-pdf-text')=>({observationId:id,value,kind,region:region(x,y),confidence:.8,verification:{status:'Unreviewed'}});

function fixture(){return{projectId:'bedford',documentId:'b61',pageId:'page-61in101',observations:[observation('p1-a','P-1',.1,.1),observation('p1-b','P-1',.4,.4),observation('p2','P-2',.2,.1),observation('rb1','RB-1',.3,.1),observation('fec','FEC',.5,.5),observation('room','124',.15,.15,'room-number-text'),observation('noise','518-22-700',.8,.9)],schedules:[{scheduleId:'finish-schedule',title:'ROOM FINISH SCHEDULE',tagColumn:'tag',verification:{status:'Confirmed'},rows:[{rowId:'row-p1',cells:[{columnId:'tag',rawText:'P-1',sourceRegion:region(.7,.2)},{columnId:'description',rawText:'PAINT',sourceRegion:region(.75,.2,.08)}]}]}],legends:[],occurrences:[],keyedNotes:[]};}

test('existing page evidence clusters into complete objects with polygons, anchors, and confidence',()=>{const result=enrichPageConstructionObjects(fixture());const p1=result.objects.find(item=>item.normalizedKey==='P1');assert.equal(p1.objectType,'finish');assert.equal(p1.objectSubtype,'Paint Finish');assert.equal(p1.graphicalRegions.length,3);assert.equal(p1.geometry.polygons.length,3);assert.equal(p1.geometry.viewportAnchors.length,3);assert.ok(p1.confidence>.8);assert.equal(result.diagnostics.objectsWithoutRegions,0);});

test('coverage diagnostics remain evidence-based and expose unsupported observations',()=>{const result=enrichPageConstructionObjects(fixture());assert.equal(result.diagnostics.evidenceCount,8);assert.equal(result.diagnostics.supportedEvidenceCount,7);assert.equal(result.diagnostics.unsupportedObservations,1);assert.equal(result.diagnostics.coveragePercent,87.5);assert.ok(result.diagnostics.coverageByCategory.Finishes>=3);assert.equal(result.diagnostics.roomCompleteness,100);assert.equal(result.diagnostics.scheduleCompleteness,100);});

test('page-object enrichment reuses the same fingerprinted page evidence',()=>{const metrics=[];const first=enrichPageConstructionObjects({...fixture(),cacheKey:'bedford:page-61in101',onMetric:value=>metrics.push(value)});metrics.length=0;const second=enrichPageConstructionObjects({...fixture(),cacheKey:'bedford:page-61in101',onMetric:value=>metrics.push(value)});assert.equal(second.diagnostics.objectsDiscovered,first.diagnostics.objectsDiscovered);assert.equal(metrics[0].operation,'object-enrichment-cache-hit');assert.equal(metrics[0].objectsDiscovered,first.diagnostics.objectsDiscovered);});

test('schedule and drawing occurrences reuse one permanent registry object without duplicate IDs',()=>{const registry=createProjectObjectRegistry();const first=applyPageObjectEnrichment(registry,enrichPageConstructionObjects(fixture()));const p1=first.objects.find(item=>item.normalizedKey==='P1');const id=p1.objectId,historyLength=registry.getObjectHistory(id).length;const second=applyPageObjectEnrichment(registry,enrichPageConstructionObjects(fixture()));assert.equal(second.objects.find(item=>item.normalizedKey==='P1').objectId,id);assert.equal(registry.getObjectHistory(id).length,historyLength);assert.equal(registry.findObjects({projectId:'bedford',pageId:'page-61in101',tag:'P-1'}).length,1);});

test('confirmed manual identity is preserved while graphical evidence expands',()=>{const registry=createProjectObjectRegistry();const manual=registry.registerObject({projectId:'bedford',drawingDocumentId:'b61',drawingPageId:'page-61in101',objectType:'finish',tag:'P-1',label:'Owner Finish',verificationState:'confirmed',identitySource:'manual',graphicalRegion:region(.1,.1)},{source:'manual'});applyPageObjectEnrichment(registry,enrichPageConstructionObjects(fixture()));const after=registry.getObject(manual.objectId);assert.equal(after.label,'Owner Finish');assert.equal(after.identitySource,'manual');assert.equal(after.graphicalRegions.length,3);});

test('room, schedule, and object cross-highlighting is bidirectional',()=>{const room={objectId:'room',objectType:'room',roomId:'124',graphicalRegion:region(.1,.1,.4,.4),graphicalRegions:[region(.1,.1,.4,.4)]};const finish={objectId:'finish',objectType:'finish',normalizedKey:'P1',roomId:'124',graphicalRegion:region(.2,.2)};const schedule={objectId:'schedule',objectType:'schedule-entry',normalizedKey:'P1',graphicalRegion:region(.7,.2)};assert.deepEqual(new Set(relatedObjectIdsForSelection(room,[room,finish,schedule])),new Set(['finish']));assert.ok(relatedObjectIdsForSelection(finish,[room,finish,schedule]).includes('room'));assert.ok(relatedObjectIdsForSelection(schedule,[room,finish,schedule]).includes('finish'));});

test('legend occurrence uses the existing legend identity rather than its fingerprint',()=>{const evidence=collectPageObjectEvidence({legends:[{legendId:'legend',legendTitle:'SIGN LEGEND',entries:[{legendEntryId:'s4',abbreviation:'S-4',label:'S-4',description:'SIGN TYPE S-4',symbolRegion:region(.1,.1),confidence:.8}]}],occurrences:[{occurrenceId:'occ',legendEntryId:'s4',symbolFingerprint:'symbol-hash',region:region(.4,.4),matchScore:1}]});assert.equal(evidence.find(item=>item.evidenceId==='occ').text,'S-4');});

test('1000 existing selectable regions hit-test within target without touching PDF rendering',()=>{const objects=Array.from({length:1000},(_,index)=>({objectId:`o${index}`,verificationState:'candidate',region:region((index%32)/33,(Math.floor(index/32)%30)/31,.015,.015),confidence:.5}));const result=hitTestDrawingObjects(objects,{x:.5,y:.5});assert.ok(result.durationMs<20,`1000-object hit test took ${result.durationMs}ms`);const source=fs.readFileSync(new URL('../src/drawing-object-enrichment.js',import.meta.url),'utf8');assert.doesNotMatch(source,/openPdfBlob|renderPdfPage|PDFDocumentProxy|specificationIndex|createConstructionGraph/);});

test('production integrates enrichment through the existing registry and overlay layer',()=>{const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/applyPageObjectEnrichment\(projectObjectRegistry,enrichment\)/);assert.match(app,/relatedObjectIdsForSelection\(selectedDrawingObject,activeDrawingObjects\)/);assert.match(app,/item\.graphicalRegions\?\.length \? item\.graphicalRegions/);assert.match(app,/Drawing object coverage/);});
