import test from 'node:test';
import assert from 'node:assert/strict';
import { parseDelimitedRows, detectStructuredReport, normalizeSubmittalRow, normalizeScheduleRow, compareStructuredRecords, acceptStructuredRecords, resolveWorkspaceReference } from '../src/structured-records.js';

test('structured report detection and aliases recognize a submittal register', () => { const rows = parseDelimitedRows('Submittal No,Spec Section,Status,Due Date\n01 32 16.15-2,28 23 00,Open,09/28/26'); assert.equal(detectStructuredReport({ fileName: 'export.csv', headers: Object.keys(rows[0]) }), 'submittal-register'); const record = normalizeSubmittalRow(rows[0], { projectId: 'bedford', importBatchId: 'batch-1', sourceRow: 2 }); assert.equal(record.recordId, 'bedford:submittal:01 32 16.15-2'); assert.equal(record.normalized.specificationSection, '28 23 00'); assert.equal(record.raw['Submittal No'], '01 32 16.15-2'); });
test('submittal reconciliation identifies new, changed, unchanged, and possibly removed records', () => { const old = normalizeSubmittalRow({ Number: 'S-1', Status: 'Open', Title: 'A' }, { projectId: 'p', importBatchId: 'old' }); const same = normalizeSubmittalRow({ Number: 'S-1', Status: 'Open', Title: 'A' }, { projectId: 'p', importBatchId: 'new' }); const changed = normalizeSubmittalRow({ Number: 'S-1', Status: 'Approved', Title: 'A' }, { projectId: 'p', importBatchId: 'new' }); assert.equal(compareStructuredRecords([old], [same]).summary.unchanged, 1); const result = compareStructuredRecords([old], [changed]); assert.equal(result.summary.changed, 1); assert.equal(result.changes[0].field, 'status'); assert.equal(compareStructuredRecords([old], []).summary.possiblyRemoved, 1); });
test('schedule records use stable activity identity and normalized dates', () => { const record = normalizeScheduleRow({ 'Activity ID': 'A-10', 'Activity Name': 'Mobilization', Start: '09/08/26', Finish: '09/12/26' }, { projectId: 'p', importBatchId: 'b' }); assert.equal(record.recordId, 'p:activity:A-10'); assert.equal(record.normalized.start, '2026-09-08'); });
test('acceptance retains source history and does not delete possibly removed records', () => { const old = normalizeSubmittalRow({ Number: 'S-1', Status: 'Open' }, { projectId: 'p', importBatchId: 'old' }); const removed = { ...old, reconciliation: { status: 'possibly-removed' } }; const saved = acceptStructuredRecords({ existing: [old], records: [], possiblyRemoved: [removed] }); assert.equal(saved.length, 1); assert.equal(saved[0].sourceHistory.length, 1); });
test('workspace aliases match explicit Building 61 but leave ambiguous values unresolved', () => { const workspaces = [{ id: 'B61', name: 'Building 61', pmisBuilding: '61' }]; assert.equal(resolveWorkspaceReference('B61', workspaces).status, 'matched'); assert.equal(resolveWorkspaceReference('Building 61', workspaces).workspaceId, 'B61'); assert.equal(resolveWorkspaceReference('61', []).status, 'unresolved'); });
