const list = value => Array.isArray(value) ? value : [];
const text = value => value === null || value === undefined ? '' : String(value).trim();
const clone = value => value === undefined ? undefined : structuredClone(value);
const hash = value => { let result = 2166136261; for (const character of text(value)) { result ^= character.charCodeAt(0); result = Math.imul(result, 16777619); } return (result >>> 0).toString(36); };

export const CONSTRUCTION_NODE_TYPES = Object.freeze([
  'project','building','floor','room','document','drawing-set','drawing-page','construction-object','drawing-note','keynote','schedule-entry','specification-document','specification-section','specification-article','field-requirement','code-requirement','change-document',
  'work-package','schedule-activity','procurement-item','material','equipment','submittal','RFI','issue','risk','question','shutdown','inspection','test','deficiency','punch-item','commissioning-item','acceptance-gate','progress-record','readiness-record',
  'photo','report','daily-log','meeting-record','correspondence','email','calendar-event','history-record','Chief-insight'
]);
export const CONSTRUCTION_EDGE_TYPES = Object.freeze([
  'contains','belongs-to','located-in','appears-on','part-of','serves','governed-by','references','requires','detailed-by','scheduled-in','specified-by','tested-by','inspected-by','commissioned-by','accepted-by','affected-by','blocked-by','blocks','depends-on','predecessor-of','successor-of','procured-through','submitted-under','documented-by','resolved-by','assigned-to','reported-in','supplements','supersedes','clarifies','modifies','has-history','derived-from','verified-by','rejected-by'
]);
const STATES = new Set(['confirmed','suggested','rejected','historical']);
const NODE_ORIGINS = new Set(['imported','parser','explicit','rule','manual','system']);
const EDGE_ORIGINS = new Set(['explicit','parser','rule','manual','imported']);
const SCOPES = new Set(['project','building','floor','room','page','object','work-package']);
const HISTORY_LIMIT = 20;

export function normalizeConstructionNode(input = {}, now = () => new Date().toISOString()) {
  const projectId = text(input.projectId), nodeType = text(input.nodeType);
  if (!projectId || !CONSTRUCTION_NODE_TYPES.includes(nodeType)) return null;
  const nodeId = text(input.nodeId) || `construction-node:${hash([projectId,nodeType,input.sourceSystem,input.sourceRecordId,input.normalizedKey].map(text).join('|'))}`;
  if (!nodeId) return null;
  const timestamp = now();
  return { nodeId, projectId, nodeType, title: text(input.title || input.label), label: text(input.label || input.title) || nodeType,
    normalizedKey: text(input.normalizedKey) || null, sourceSystem: text(input.sourceSystem) || 'mission-companion', sourceRecordId: text(input.sourceRecordId) || null,
    sourceDocumentId: text(input.sourceDocumentId) || null, sourcePageId: text(input.sourcePageId) || null, sourceObjectId: text(input.sourceObjectId) || null,
    buildingId: text(input.buildingId) || null, floorId: text(input.floorId) || null, roomId: text(input.roomId) || null, trade: text(input.trade) || null,
    system: text(input.system) || null, status: text(input.status) || null, verificationState: STATES.has(text(input.verificationState)) ? text(input.verificationState) : 'suggested',
    origin: NODE_ORIGINS.has(text(input.origin)) ? text(input.origin) : 'system', freshness: { sourceUpdatedAt: text(input.freshness?.sourceUpdatedAt) || null, ingestedAt: text(input.freshness?.ingestedAt) || timestamp, evaluatedAt: text(input.freshness?.evaluatedAt) || timestamp, stale: Boolean(input.freshness?.stale) },
    metadata: input.metadata && typeof input.metadata === 'object' ? clone(input.metadata) : {}, createdAt: text(input.createdAt) || timestamp, updatedAt: text(input.updatedAt) || timestamp,
    auditHistory: list(input.auditHistory).slice(-HISTORY_LIMIT).map(clone) };
}

export function normalizeConstructionEdge(input = {}, nodes = new Map(), now = () => new Date().toISOString()) {
  const projectId = text(input.projectId), sourceNodeId = text(input.sourceNodeId), targetNodeId = text(input.targetNodeId), edgeType = text(input.edgeType);
  const source = nodes.get(sourceNodeId), target = nodes.get(targetNodeId);
  if (!projectId || !source || !target || source.projectId !== projectId || target.projectId !== projectId || !CONSTRUCTION_EDGE_TYPES.includes(edgeType)) return null;
  const revisionKey = text(input.revisionKey) || 'active';
  const edgeId = text(input.edgeId) || `construction-edge:${hash([projectId,sourceNodeId,targetNodeId,edgeType,revisionKey].join('|'))}`;
  const timestamp = now();
  return { edgeId, projectId, sourceNodeId, targetNodeId, edgeType, direction: ['outgoing','incoming','bidirectional'].includes(input.direction) ? input.direction : 'outgoing', scope: SCOPES.has(text(input.scope)) ? text(input.scope) : 'object',
    confidence: Math.max(0, Math.min(1, Number(input.confidence) || 0)), verificationState: STATES.has(text(input.verificationState)) ? text(input.verificationState) : 'suggested', origin: EDGE_ORIGINS.has(text(input.origin)) ? text(input.origin) : 'rule',
    evidence: list(input.evidence).filter(item => item && typeof item === 'object').map(clone), sourceDocumentId: text(input.sourceDocumentId) || null, sourcePageId: text(input.sourcePageId) || null, sourceObjectId: text(input.sourceObjectId) || null,
    effectiveDate: text(input.effectiveDate) || null, supersededAt: text(input.supersededAt) || null, revisionKey, createdAt: text(input.createdAt) || timestamp, updatedAt: text(input.updatedAt) || timestamp,
    auditHistory: list(input.auditHistory).slice(-HISTORY_LIMIT).map(clone), metadata: input.metadata && typeof input.metadata === 'object' ? clone(input.metadata) : {} };
}

export function createConstructionGraph({ persistence = null, now = () => new Date().toISOString(), relationshipEngine = null, objectRegistry = null, onDiagnostic = () => {} } = {}) {
  const nodes = new Map(), edges = new Map(), history = [], failures = []; let hydrated = false, queue = Promise.resolve(), cacheHits = 0, cacheMisses = 0;
  const persist = (method, record) => { if (!persistence?.[method]) return; const started = performance.now(); queue = queue.then(() => persistence[method](clone(record))).catch(error => { failures.push({ category:'construction-graph-persistence-failure', message:error?.message || String(error), contained:true, timestamp:now() }); }).finally(() => onDiagnostic({ operation:method, durationMs:performance.now()-started })); };
  const recordHistory = (action, record, prior = null) => { const entry = { historyId:`construction-history:${hash(`${action}|${record.nodeId || record.edgeId}|${now()}|${history.length}`)}`, projectId:record.projectId, action, recordId:record.nodeId || record.edgeId, prior:clone(prior), current:clone(record), createdAt:now() }; history.push(entry); persist('putHistory', entry); return entry; };
  const api = {
    async load(projectId = '') { if (persistence) { const [savedNodes,savedEdges] = await Promise.all([persistence.loadNodes?.(projectId) || [], persistence.loadEdges?.(projectId) || []]); for (const item of list(savedNodes)) { const node=normalizeConstructionNode(item,now); if(node) nodes.set(node.nodeId,node); } for (const item of list(savedEdges)) { const edge=normalizeConstructionEdge(item,nodes,now); if(edge) edges.set(edge.edgeId,edge); } } hydrated=true; return api.getDiagnostics(projectId); },
    ready: () => hydrated || !persistence,
    flush: () => queue,
    registerNode(input) { const node=normalizeConstructionNode(input,now); if(!node) return null; const prior=nodes.get(node.nodeId); if(prior?.origin==='manual' && node.origin!=='manual') return clone(prior); const next={...node,createdAt:prior?.createdAt||node.createdAt,auditHistory:[...list(prior?.auditHistory),{action:prior?'updated':'created',time:now(),source:node.origin}].slice(-HISTORY_LIMIT)}; nodes.set(next.nodeId,next); persist('putNode',next); recordHistory(prior?'node-updated':'node-created',next,prior); return clone(next); },
    getNode(nodeId) { const node=nodes.get(text(nodeId)); node?cacheHits++:cacheMisses++; return node?clone(node):null; },
    findNodes({projectId='',nodeTypes=[],verificationStates=['confirmed','suggested','historical'],sourcePageId='',sourceObjectId='',limit=200}={}) { const types=new Set(list(nodeTypes)), states=new Set(list(verificationStates)); return [...nodes.values()].filter(n=>(!projectId||n.projectId===projectId)&&(!types.size||types.has(n.nodeType))&&states.has(n.verificationState)&&(!sourcePageId||n.sourcePageId===sourcePageId)&&(!sourceObjectId||n.sourceObjectId===sourceObjectId)).sort((a,b)=>a.nodeType.localeCompare(b.nodeType)||a.label.localeCompare(b.label)||a.nodeId.localeCompare(b.nodeId)).slice(0,Math.max(1,Math.min(1000,Number(limit)||200))).map(clone); },
    registerEdge(input) { const edge=normalizeConstructionEdge(input,nodes,now); if(!edge) return null; const same=[...edges.values()].find(e=>e.projectId===edge.projectId&&e.sourceNodeId===edge.sourceNodeId&&e.targetNodeId===edge.targetNodeId&&e.edgeType===edge.edgeType&&e.revisionKey===edge.revisionKey); if(same?.verificationState==='rejected'&&same.origin==='manual'&&edge.origin!=='manual') return clone(same); const prior=edges.get(edge.edgeId)||same; const next={...edge,edgeId:prior?.edgeId||edge.edgeId,createdAt:prior?.createdAt||edge.createdAt,auditHistory:[...list(prior?.auditHistory),{action:prior?'updated':'created',time:now(),source:edge.origin}].slice(-HISTORY_LIMIT)}; edges.set(next.edgeId,next); persist('putEdge',next); recordHistory(prior?'edge-updated':'edge-created',next,prior); return clone(next); },
    getEdge(edgeId) { const edge=edges.get(text(edgeId)); return edge?clone(edge):null; },
    findEdges({projectId='',nodeId='',edgeTypes=[],verificationStates=['confirmed','suggested','historical'],direction='',limit=200}={}) { const types=new Set(list(edgeTypes)),states=new Set(list(verificationStates)); return [...edges.values()].filter(e=>(!projectId||e.projectId===projectId)&&(!types.size||types.has(e.edgeType))&&states.has(e.verificationState)&&(!nodeId||(direction==='outgoing'?e.sourceNodeId===nodeId:direction==='incoming'?e.targetNodeId===nodeId:e.sourceNodeId===nodeId||e.targetNodeId===nodeId))).sort((a,b)=>a.edgeType.localeCompare(b.edgeType)||a.edgeId.localeCompare(b.edgeId)).slice(0,Math.max(1,Math.min(1000,Number(limit)||200))).map(clone); },
    getNeighbors(nodeId,options={}) { const node=nodes.get(text(nodeId)); if(!node)return[]; return api.findEdges({...options,projectId:node.projectId,nodeId:node.nodeId}).map(edge=>({edge,node:api.getNode(edge.sourceNodeId===node.nodeId?edge.targetNodeId:edge.sourceNodeId)})).filter(x=>x.node&&(!options.nodeTypes?.length||options.nodeTypes.includes(x.node.nodeType))); },
    traverse(nodeId,options={}) { const start=nodes.get(text(nodeId)); if(!start)return{nodes:[],edges:[],paths:[],truncated:false}; const maxDepth=Math.max(0,Math.min(8,Number(options.maxDepth)||2)),limit=Math.max(1,Math.min(500,Number(options.limit)||100)); const queueItems=[{id:start.nodeId,path:[start.nodeId],edgePath:[]}],visited=new Set([start.nodeId]),resultNodes=[clone(start)],resultEdges=[],paths=[]; let truncated=false; while(queueItems.length){const current=queueItems.shift();if(current.edgePath.length>=maxDepth)continue;for(const pair of api.getNeighbors(current.id,options)){if(visited.has(pair.node.nodeId))continue;if(resultNodes.length>=limit){truncated=true;break;}visited.add(pair.node.nodeId);resultNodes.push(pair.node);resultEdges.push(pair.edge);paths.push({nodeIds:[...current.path,pair.node.nodeId],edgeIds:[...current.edgePath,pair.edge.edgeId]});queueItems.push({id:pair.node.nodeId,path:[...current.path,pair.node.nodeId],edgePath:[...current.edgePath,pair.edge.edgeId]});}if(truncated)break;} return{nodes:resultNodes,edges:resultEdges,paths,truncated,maxDepth,limit}; },
    getPath(sourceNodeId,targetNodeId,options={}) { const source=nodes.get(text(sourceNodeId)),target=nodes.get(text(targetNodeId));if(!source||!target||source.projectId!==target.projectId)return null;const traversal=api.traverse(source.nodeId,{...options,maxDepth:options.maxDepth||5});const path=traversal.paths.find(p=>p.nodeIds.at(-1)===target.nodeId);return path?{projectId:source.projectId,nodes:path.nodeIds.map(api.getNode),edges:path.edgeIds.map(api.getEdge)}:null; },
    getRequirements(nodeId,options={}) { return api.getNeighbors(nodeId,{...options,edgeTypes:['governed-by','requires','specified-by'],nodeTypes:['specification-section','specification-article','field-requirement']}).filter(x=>x.edge.verificationState!=='rejected'); },
    getOperationalStatus(nodeId,options={}) { return api.getNeighbors(nodeId,{...options,nodeTypes:['work-package','schedule-activity','procurement-item','submittal','RFI','issue','risk','question','shutdown','inspection','test','deficiency','punch-item','commissioning-item','acceptance-gate','progress-record','readiness-record']}); },
    getDependencies(nodeId,options={}) { return api.getNeighbors(nodeId,{...options,edgeTypes:['blocked-by','blocks','depends-on','predecessor-of','successor-of','requires']}); },
    getImpacts(nodeId,options={}) { const affects=api.getNeighbors(nodeId,{...options,direction:'outgoing',edgeTypes:['affects','affected-by','blocks','modifies','supersedes','supplements']});const affectedBy=api.getNeighbors(nodeId,{...options,direction:'incoming',edgeTypes:['affected-by','blocks','modifies','supersedes','supplements']});return{affects,affectedBy}; },
    getReadiness(nodeId,options={}) { return options.readinessEngine?.calculate?.(nodeId,api,options)||null; },
    getHistory(nodeId,{limit=100}={}) { return history.filter(item=>item.recordId===nodeId||api.getEdge(item.recordId)?.sourceNodeId===nodeId||api.getEdge(item.recordId)?.targetNodeId===nodeId).slice(-Math.max(1,Math.min(500,limit))).map(clone); },
    getConstructionSummary(nodeId,options={}) { const node=api.getNode(nodeId);if(!node)return null;const requirements=api.getRequirements(nodeId,options),operations=api.getOperationalStatus(nodeId,options),dependencies=api.getDependencies(nodeId,options),impacts=api.getImpacts(nodeId,options);return{node,identity:{roomId:node.roomId,buildingId:node.buildingId,drawingPageId:node.sourcePageId,trade:node.trade,system:node.system},requirements:{confirmed:requirements.filter(x=>x.edge.verificationState==='confirmed'),suggested:requirements.filter(x=>x.edge.verificationState==='suggested')},operations,dependencies,impacts,readiness:api.getReadiness(nodeId,options),history:api.getHistory(nodeId),warnings:clone(failures)}; },
    validateProjectGraph(projectId) { const findings=[];for(const edge of edges.values()){if(edge.projectId!==projectId)continue;const source=nodes.get(edge.sourceNodeId),target=nodes.get(edge.targetNodeId);if(!source)findings.push({code:'missing-source-node',edgeId:edge.edgeId});if(!target)findings.push({code:'missing-target-node',edgeId:edge.edgeId});if(source&&target&&(source.projectId!==projectId||target.projectId!==projectId))findings.push({code:'cross-project-edge',edgeId:edge.edgeId});if(!edge.evidence.length&&!['manual','imported'].includes(edge.origin))findings.push({code:'missing-evidence',edgeId:edge.edgeId});}return findings; },
    getDiagnostics(projectId='') { const projectNodes=[...nodes.values()].filter(n=>!projectId||n.projectId===projectId),projectEdges=[...edges.values()].filter(e=>!projectId||e.projectId===projectId),broken=projectEdges.filter(e=>!nodes.has(e.sourceNodeId)||!nodes.has(e.targetNodeId));return{nodeCount:projectNodes.length,edgeCount:projectEdges.length,orphanNodeCount:projectNodes.filter(n=>!projectEdges.some(e=>e.sourceNodeId===n.nodeId||e.targetNodeId===n.nodeId)).length,brokenEdgeCount:broken.length,cacheHits,cacheMisses,persistenceBackend:persistence?'IndexedDB':'memory',failureCount:failures.length,historyPayloadLimit:HISTORY_LIMIT}; },
    adaptRelationshipEngine(projectId) { if(!relationshipEngine)return{nodes:0,edges:0};let nodeCount=0,edgeCount=0;for(const entity of relationshipEngine.entities?.({projectId,verificationStates:['confirmed','suggested','rejected','historical']})||[]){const mapped=api.registerNode({nodeId:entity.sourceObjectId||entity.entityId,projectId:entity.projectId,nodeType:entity.entityType==='drawing-object'?'construction-object':entity.entityType,sourceSystem:'project-relationship-engine',sourceRecordId:entity.entityId,sourceDocumentId:entity.sourceDocumentId,sourcePageId:entity.sourcePageId,sourceObjectId:entity.sourceObjectId,title:entity.title,label:entity.label,normalizedKey:entity.normalizedKey,verificationState:entity.verificationState,origin:entity.origin,metadata:entity.metadata,createdAt:entity.createdAt,updatedAt:entity.updatedAt});if(mapped)nodeCount++;}for(const entity of relationshipEngine.entities?.({projectId,verificationStates:['confirmed','suggested','rejected','historical']})||[]){for(const relationship of relationshipEngine.getRelationships?.(entity.entityId,{projectId,includeRejected:true,limit:500})||[]){const source=api.findNodes({projectId,limit:1000}).find(n=>n.sourceRecordId===relationship.sourceEntityId),target=api.findNodes({projectId,limit:1000}).find(n=>n.sourceRecordId===relationship.targetEntityId);if(source&&target&&api.registerEdge({edgeId:relationship.relationshipId,projectId,sourceNodeId:source.nodeId,targetNodeId:target.nodeId,edgeType:relationship.relationshipType==='related-to'?'references':relationship.relationshipType,confidence:relationship.confidence,verificationState:relationship.verificationState,origin:relationship.origin,evidence:relationship.evidence,sourceDocumentId:relationship.sourceDocumentId,sourcePageId:relationship.sourcePageId,sourceObjectId:relationship.sourceObjectId,revisionKey:relationship.revisionKey,createdAt:relationship.createdAt,updatedAt:relationship.updatedAt}))edgeCount++;}}return{nodes:nodeCount,edges:edgeCount}; },
    adaptObjectRegistry(projectId) { let count=0;for(const object of objectRegistry?.findObjects?.({projectId,includeRejected:true,limit:1000})||[]){if(api.registerNode({nodeId:object.objectId,projectId,nodeType:'construction-object',sourceSystem:'project-object-registry',sourceRecordId:object.objectId,sourceDocumentId:object.drawingDocumentId,sourcePageId:object.drawingPageId,sourceObjectId:object.objectId,title:object.label,label:object.label,normalizedKey:object.normalizedKey,buildingId:object.buildingId,roomId:object.roomId,trade:object.trade,system:object.system,verificationState:object.verificationState==='candidate'?'suggested':object.verificationState,origin:object.identitySource==='parser'?'parser':object.identitySource,metadata:{objectType:object.objectType,tag:object.tag,aliases:object.aliases},createdAt:object.createdAt,updatedAt:object.updatedAt}))count++;}return count;}
  };
  return api;
}
